SELECT 'CC_CUSTOMER' tabname, COUNT(*) norows FROM CC_CUSTOMER union
SELECT 'CC_CUSTORDER' tabname, COUNT(*) FROM CC_CUSTORDER union
SELECT 'CC_SUPPLIER' tabname,COUNT(*) FROM CC_SUPPLIER union
SELECT 'CC_STAFF' tabname,COUNT(*) FROM CC_STAFF union
SELECT 'CC_STOCK' tabname,COUNT(*) FROM CC_STOCK union
SELECT 'CC_SUPPORDER' tabname,COUNT(*) FROM CC_SUPPORDER union
SELECT 'CC_STOCKSALE' tabname,COUNT(*) FROM STOCKSALE union
SELECT 'CC_PURCHASESTOCK' tabname,COUNT(*) FROM PURCHASESTOCK;
set verify off;
SELECT SYSDATE now, '&name' me, substr(user,0,10) uname FROM DUAL;